include:
  - project: 'build_server/gitlab_ci_includes'
    file: 'software_catalogue.yml'

build_with_backbone_18.04_and_test:
    image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-ric-backbone_ubuntu:18.04
    stage: test
    script:
      - echo $PWD
      - autoproj test enable .
      - autoproj update .
      - autoproj osdeps
      - amake .
      - ./build/test/templ-test --log_level=all
